[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ['npm ci --omit=dev --legacy-peer-deps']

[phases.build]
cmds = ['npm run build || echo "No build script found, skipping..."']

[start]
cmd = 'npm start'
